name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 flake8

    - name: Lint code
      run: |
        autopep8 --in-place --recursive --ignore=F841,F401,W504 .
        flake8 --exclude=.git,__pycache__,venv --max-line-length=88 .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          dist

    - name: List contents of dist directory
      run: ls -R dist
